version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    ports:
      - 8090:80
      - 8443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/letsencrypt/live/unitedsportshub.com  # Adjust to the actual path on your host machine