version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    expose:
      - "8090"
    environment:
      - APP_PORT=8090
  
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cert.pem:/etc/letsencrypt/live/unitedsportshub.com/cert.pem:ro
      - ./key.pem:/etc/letsencrypt/live/unitedsportshub.com/privkey.pem:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
